name: React CI/CD

on:
  push:
    branches: [main]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Create .env.production file
        run: |
          echo "REACT_APP_APP_KEY=${{ secrets.REACT_APP_APP_KEY }}" > .env.production
          echo "REACT_APP_APP_SECRET=${{ secrets.REACT_APP_APP_SECRET }}" > .env.production
          echo "REACT_APP_BEARER_KEY=${{ secrets.REACT_APP_BEARER_KEY }}" >> .env.production
          echo "REACT_APP_HOST=${{ secrets.REACT_APP_HOST }}" >> .env.production

      - name: Build React app
        run: npm run build

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: build

  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: build

      - name: Create remote temporary directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /tmp/build

      - name: Copy build file to tmp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: 'build/*'
          target: '/tmp/build'

      - name: Move build file and restart nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/html
            sudo cp -r /tmp/build/* /var/www/html
            sudo rm -rf /tmp/build
            sudo systemctl restart nginx
